		title   "LCD"
        list    p=16f84A
        radix   hex
        include "p16f84A.inc"
        
COUNT1  EQU    	d'12'
COUNT2	EQU		d'13'
COUNT3	EQU		d'14'
      	ORG    	0x0
		GOTO	START
		ORG		0x04
		BTFSC	INTCON,INTF		;interrupts
		GOTO	INTRB0
		BTFSC	INTCON,RBIF
		GOTO	INTRB4
		BTFSC	INTCON,T0IF
		GOTO	TIMERZ

		;init I/O ports
START	BSF		STATUS,RP0
		CLRF	TRISA		;LCD DB(4,7) = RA(0-3)	//	RS = RA4
		CLRF	TRISB		;LCD ENABLE = RB1	// RED LED = RB2
							;GREEN LED = RB3	//	BUZZER=RB0
		BSF		TRISB,4		;left
		BSF		TRISB,5		;right
		BSF		TRISB,6		;up/down
		BSF		TRISB,7		;confirm
		MOVLW	B'10000111'
		MOVWF	OPTION_REG
		BCF		STATUS,RP0
		CLRF	PORTA
		CLRF	PORTB
		CLRF	INTCON
		BSF		INTCON,INTE
		BSF		INTCON,RBIE
		BSF		INTCON,T0IE
		BSF		INTCON,GIE
		
	;INIT ROUTINE
		CALL	DELAY
		MOVLW	b'00010'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'00010'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'01000'
		MOVWF	PORTA
		CALL 	ET
	;DISPLAY ON/OFF CONTROL
		MOVLW	b'00000'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'01111'
		MOVWF	PORTA
		CALL 	ET
	;CLEAR DISPLAY
		MOVLW	b'00000'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'00001'
		MOVWF	PORTA
		CALL 	ET
	;ENTRY MODE SET
		MOVLW	b'00000'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'00100'
		MOVWF	PORTA
		CALL 	ET
		NOP

ET		BSF PORTB,1
		NOP
		BCF	PORTB,1
		CALL DELAY			;change to <40ms to write faster
		RETURN

;interrupt routines
INTRB4	CALL	DELAY1
		BTFSS	PORTB,4
		BSF		PORTB,1
		BTFSC	PORTB,4
		BCF		PORTB,1
		BCF		INTCON,RBIF
		RETFIE

INTRB0	CALL 	DELAY1
		BTFSS	PORTB,0
		CLRF	PORTA
		BCF		INTCON,INTF
		RETFIE

TIMERZ	MOVLW	d'16'
		MOVWF	COUNT1
		DECFSZ	COUNT1,F
		GOTO	FINISH
		INCF	PORTA
		CLRF	TMR0
		MOVLW	d'16'
		MOVWF	COUNT1
FINISH	BCF		INTCON,T0IF
		RETFIE

;DELAYS
DELAY   MOVLW   H'0'		;40ms delay
        MOVWF   COUNT1
		MOVLW	d'52'
        MOVWF	COUNT2
LOOP3   INCFSZ	COUNT1,F
      	GOTO    LOOP3
		DECFSZ	COUNT2,F
		GOTO	LOOP3 
		RETURN


DELAY1  MOVLW    H'06'		;1ms delay
        MOVWF    COUNT1
            
LOOP    NOP
		INCFSZ	COUNT1,F
        GOTO    LOOP
        RETURN

END