		title   "LCD"
        list    p=16f84A
        radix   hex
        include "p16f84A.inc"
        
COUNT1  EQU    	d'12'
COUNT2	EQU		d'13'
COUNT3	EQU		d'14'
P1		EQU		d'15'
P2		EQU		d'16'
P3		EQU		d'17'
P4		EQU		d'18'
P5		EQU		d'19'
P6		EQU		d'20'
P7		EQU		d'21'
P8		EQU		d'22'
P9		EQU		d'23'
P10		EQU		d'24'
P11		EQU		d'25'
P12		EQU		d'26'
FLAG	EQU		d'27'

      	ORG    	0x0
		GOTO	START
		ORG		0x04
		BTFSC	INTCON,INTF		;interrupts
		GOTO	INTRB0
		BTFSC	INTCON,RBIF
		GOTO	INTRB4
		BTFSC	INTCON,T0IF
		GOTO	TIMERZ
		

		;init I/O ports
START	BSF		STATUS,RP0
		CLRF	TRISA		;LCD DB(4,7) = RA(0-3)	//	RS = RA4
		CLRF	TRISB		;LCD ENABLE = RB1	// RED LED = RB2
							;GREEN LED = RB3	//	BUZZER=RB0
		BSF		TRISB,4		;left
		BSF		TRISB,5		;right
		BSF		TRISB,6		;up/down
		BSF		TRISB,7		;confirm
		MOVLW	B'10000111'
		MOVWF	OPTION_REG
		BCF		STATUS,RP0
		CLRF	PORTA
		CLRF	PORTB
		CLRF	INTCON
		BSF		INTCON,INTE
		BSF		INTCON,RBIE
		BSF		INTCON,T0IE
		BSF		INTCON,GIE
		CALL	INITPOS
		CALL	WLCM
		CALL	MENU
		
	;INIT ROUTINE
		CALL	DELAY
		MOVLW	b'00010'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'00010'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'01000'
		MOVWF	PORTA
		CALL 	ET
	;DISPLAY ON/OFF CONTROL
		MOVLW	b'00000'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'01111'
		MOVWF	PORTA
		CALL 	ET
	;CLEAR DISPLAY
		MOVLW	b'00000'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'00001'
		MOVWF	PORTA
		CALL 	ET
	;ENTRY MODE SET
		MOVLW	b'00000'
		MOVWF	PORTA
		CALL 	ET
		MOVLW	b'00100'
		MOVWF	PORTA
		CALL 	ET
		NOP

ET		BSF PORTB,1
		NOP
		BCF	PORTB,1
		CALL DELAY			;change to <40ms to write faster
		RETURN

;interrupt routines
INTRB4	CALL	DELAY1
		BTFSS	PORTB,4
		BSF		PORTB,1
		BTFSC	PORTB,4
		BCF		PORTB,1
		BCF		INTCON,RBIF
		RETFIE

INTRB0	CALL 	DELAY1
		BTFSS	PORTB,0
		CLRF	PORTA
		BCF		INTCON,INTF
		RETFIE

TIMERZ	MOVLW	d'16'
		MOVWF	COUNT1
		DECFSZ	COUNT1,F
		GOTO	FINISH
		INCF	PORTA
		CLRF	TMR0
		MOVLW	d'16'
		MOVWF	COUNT1
FINISH	BCF		INTCON,T0IF
		RETFIE

;DELAYS
DELAY   MOVLW   H'0'		;40ms delay
        MOVWF   COUNT1
		MOVLW	d'52'
        MOVWF	COUNT2
LOOP3   INCFSZ	COUNT1,F
      	GOTO    LOOP3
		DECFSZ	COUNT2,F
		GOTO	LOOP3 
		RETURN


DELAY1  MOVLW    H'06'		;1ms delay
        MOVWF    COUNT1
            
LOOP    NOP
		INCFSZ	COUNT1,F
        GOTO    LOOP
        RETURN

INITPOS	MOVLW	D'12'
		MOVWF	P1
		MOVLW	D'10'
		MOVWF	P2
		MOVLW	D'14'
		MOVWF	P3
		MOVLW	D'15'
		MOVWF	P4
		MOVLW	D'11'
		MOVWF	P5
		MOVLW	D'13'
		MOVWF	P6
		MOVLW	D'11'
		MOVWF	P7
		MOVLW	D'13'
		MOVWF	P8
		MOVLW	D'15'
		MOVWF	P9
		MOVLW	D'12'
		MOVWF	P10
		MOVLW	D'10'
		MOVWF	P11
		MOVLW	D'14'
		MOVWF	P12

WLCM	CALL	PRINTM
		CALL	PRINTE
		CALL	PRINTM
		CALL	PRINTSP
		CALL	PRINTG
		CALL	PRINTA
		CALL	PRINTM
		CALL	PRINTE
		CALL	CLEAR

MENU	CALL	PRINTM
		CALL	PRINTO
		CALL	PRINTD
		CALL	PRINTE
		CALL	PRINTSP
		CALL	PRINT1
		CALL	PRINTSP
		CALL	PRINT2
		CALL	PRINTSP
		CALL	PRINT3
		

;LETTERS FUNCTIONS
PRINTM	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11101'
		MOVWF	PORTA
		CALL	ET

PRINTE	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET

PRINTO	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11111'
		MOVWF	PORTA
		CALL	ET

PRINTD	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET

PRINT1	MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10001'
		MOVWF	PORTA
		CALL	ET

PRINT2	MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10010'
		MOVWF	PORTA
		CALL	ET

PRINT3	MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET

PRINTA	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10001'
		MOVWF	PORTA
		CALL	ET

PRINTB	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10010'
		MOVWF	PORTA
		CALL	ET

PRINTC	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET

PRINTF	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10110'
		MOVWF	PORTA
		CALL	ET

PRINTF	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10111'
		MOVWF	PORTA
		CALL	ET

PRINTST	MOVLW	B'10010'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11010'
		MOVWF	PORTA
		CALL	ET

PRINTSP	MOVLW	B'11010'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10000'
		MOVWF	PORTA
		CALL	ET

PRINTSQ	MOVLW	b'11101'
		MOVWF 	PORTA
		CALL 	ET
		MOVLW	b'11011'
		MOVWF 	PORTA
		CALL 	ET	
		RETURN
;CLEAR FUNCTION
CLEAR	MOVLW	B'00000'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'00001'
		MOVWF	PORTA
		CALL	ET		

END